<?php
namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder {
    public function run(): void {
        Product::truncate();
        $products = [
            // EXPORTS
            ['name'=>'Mill Scale','slug'=>'mill-scale','type'=>'export','category'=>'Industrial','detail_title'=>'Premium-Grade Mill Scale from Bangladesh','icon'=>'⚙️','description'=>'High-grade mill scale produced as a byproduct of hot rolling operations.','image'=>'/images/products/exports/mill-scale/mill-1.jpeg','gallery_images'=>json_encode(['/images/products/exports/mill-scale/mill-2.jpeg','/images/products/exports/mill-scale/mill-3.jpeg']),'specs'=>json_encode(['HS Code'=>'2619.00','Fe Content'=>'≥ 68%','Moisture'=>'≤ 3%','Packing'=>'Bulk / Jumbo Bags','Min Order'=>'500 MT','Origin'=>'Bangladesh']),'tags'=>json_encode(['Metallurgy','Steel Making','Industrial']),'sort_order'=>1,'is_active'=>true],
            ['name'=>'Zinc Ash / Zinc Oxide','slug'=>'zinc-oxide','type'=>'export','category'=>'Industrial By-product','detail_title'=>'Industrial Zinc Ash & Zinc Oxide Solutions','icon'=>'🔬','description'=>'Zinc ash recovered from galvanizing and die-casting operations.','image'=>'/images/products/exports/zinc-ash/drums-closeup.jpeg','gallery_images'=>json_encode(['/images/products/exports/zinc-ash/zinc-3.jpeg','/images/products/exports/zinc-ash/drums-2.jpeg']),'specs'=>json_encode(['HS Code'=>'2620.19','Zn Content'=>'60–80%','Form'=>'Powder / Granule','Packing'=>'Jumbo Bags / Drums','Min Order'=>'10 MT','Origin'=>'Bangladesh']),'tags'=>json_encode(['Industrial','Recycled','Zinc']),'sort_order'=>2,'is_active'=>true],
            ['name'=>'PET Flakes','slug'=>'pet-flakes','type'=>'export','category'=>'Recycled Materials','detail_title'=>'Clean-Washed Recycled PET Flakes','icon'=>'♻️','description'=>'Post-consumer PET bottle flakes, clean-washed and dried for textile and packaging recycling.','image'=>'/images/products/exports/pet-flakes/flakes-2.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'3915.10','Purity'=>'≥ 98%','Moisture'=>'≤ 1%','Packing'=>'Bales','Min Order'=>'20 MT','Origin'=>'Bangladesh']),'tags'=>json_encode(['Recycled','Plastic','Eco-Friendly']),'sort_order'=>3,'is_active'=>true],
            ['name'=>'Leather Goods','slug'=>'leather-goods','type'=>'export','category'=>'Manufactured Goods','detail_title'=>'Premium Bangladeshi Leather Goods','icon'=>'👜','description'=>'High-quality leather bags, wallets, belts, and accessories from certified Bangladeshi manufacturers.','image'=>'/images/products/exports/leather/leather-2.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'4202','Material'=>'Full-grain / Split leather','MOQ'=>'500 pcs','Lead Time'=>'30-45 days','Origin'=>'Bangladesh']),'tags'=>json_encode(['Leather','Fashion','Export']),'sort_order'=>4,'is_active'=>true],
            ['name'=>'Fresh Vegetables & Fruits','slug'=>'vegetables-fruits','type'=>'export','category'=>'Agri Products','detail_title'=>'Fresh Certified Bangladeshi Produce','icon'=>'🥬','description'=>'Certified fresh vegetables and tropical fruits from Bangladeshi farms to Middle East and European markets.','image'=>'/images/products/exports/vegetables/cabbage-field.jpeg','gallery_images'=>json_encode(['/images/products/exports/vegetables/produce-1.jpeg']),'specs'=>json_encode(['HS Code'=>'0701-0714','Certification'=>'Phytosanitary','Packing'=>'Cartons / Crates','Min Order'=>'5 MT','Season'=>'Year-round','Origin'=>'Bangladesh']),'tags'=>json_encode(['Agri','Fresh','Certified']),'sort_order'=>5,'is_active'=>true],
            ['name'=>'Jute & Jute Products','slug'=>'jute-products','type'=>'export','category'=>'Natural Fibres','detail_title'=>'Raw Jute & Jute-Made Products','icon'=>'🌿','description'=>'Raw jute, hessian cloth, jute bags, jute yarn, and value-added jute products from Bangladesh.','image'=>'/images/products/exports/jute/jute-1.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'5303-5310','Grade'=>'TD3 / White C','Moisture'=>'≤ 14%','Packing'=>'Bales','Min Order'=>'20 MT','Origin'=>'Bangladesh']),'tags'=>json_encode(['Jute','Natural','Eco-Friendly']),'sort_order'=>6,'is_active'=>true],
            ['name'=>'Ready-Made Garments','slug'=>'ready-made-garments','type'=>'export','category'=>'Textile','detail_title'=>'Quality RMG from Certified Factories','icon'=>'👕','description'=>'Ready-made garments sourced from BGMEA-certified Bangladeshi factories meeting international compliance standards.','image'=>'/images/products/exports/jute/jute-1.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'6101-6217','Certification'=>'GOTS / OEKO-TEX','MOQ'=>'1000 pcs','Lead Time'=>'45-60 days','Origin'=>'Bangladesh']),'tags'=>json_encode(['Garments','Textile','RMG']),'sort_order'=>7,'is_active'=>true],
            // IMPORTS
            ['name'=>'Aggregate Stones','slug'=>'aggregate-stones','type'=>'import','category'=>'Construction Materials','detail_title'=>'Premium Gabbro & Limestone Aggregate','icon'=>'🪨','description'=>'High-grade gabbro and limestone aggregate from Oman and Malaysia for road and building construction.','image'=>'/images/products/imports/aggregate/aggregate-1.png','gallery_images'=>json_encode(['/images/products/imports/aggregate/aggregate-3.jpeg','/images/products/imports/aggregate/gabbro-3.jpeg']),'specs'=>json_encode(['HS Code'=>'2517.10','Grade'=>'Gabbro / Limestone','Size'=>'10-20mm / 20-40mm','Moisture'=>'≤ 3%','Origin'=>'Oman / Malaysia']),'use_cases'=>json_encode(['Road base and sub-base construction','Concrete aggregate for buildings','Railway ballast','Drainage and filtration']),'tags'=>json_encode(['Construction','Aggregate','Gabbro']),'sort_order'=>1,'is_active'=>true],
            ['name'=>'Coal','slug'=>'coal','type'=>'import','category'=>'Energy','detail_title'=>'Thermal & Coking Coal','icon'=>'⛏️','description'=>'Thermal and coking coal from South Africa and Indonesia for power plants, brick kilns, and steel mills.','image'=>'/images/products/imports/coal/yard-1.jpeg','gallery_images'=>json_encode(['/images/products/imports/coal/coal-2.jpeg']),'specs'=>json_encode(['HS Code'=>'2701','Type'=>'Thermal / Coking','GCV'=>'4500-6000 kcal/kg','Sulphur'=>'≤ 1%','Origin'=>'South Africa / Indonesia']),'use_cases'=>json_encode(['Power plant fuel','Brick kiln fuel','Steel mill coking coal','Cement plant fuel']),'tags'=>json_encode(['Energy','Coal','Industrial']),'sort_order'=>2,'is_active'=>true],
            ['name'=>'Steel Scrap (HMS)','slug'=>'steel-scrap-hms','type'=>'import','category'=>'Metals','detail_title'=>'Heavy Melting Steel Scrap (HMS 1 & 2)','icon'=>'🔩','description'=>'Heavy melting steel scrap (HMS 1 & 2) from Europe and North America for domestic re-rolling mills.','image'=>'/images/products/imports/steel-scrap/scrap-1.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'7204','Grade'=>'HMS 1 & 2','Density'=>'≥ 1.1 MT/m³','Max Size'=>'1500mm x 600mm','Origin'=>'Europe / USA']),'use_cases'=>json_encode(['Re-rolling mill feedstock','Electric arc furnace (EAF) input','Induction furnace charge material']),'tags'=>json_encode(['Metal','Scrap','Steel']),'sort_order'=>3,'is_active'=>true],
            ['name'=>'Limestone','slug'=>'limestone','type'=>'import','category'=>'Construction Materials','detail_title'=>'Industrial & Construction Limestone','icon'=>'🏗️','description'=>'High-calcium limestone for cement plant feed, industrial lime production, and construction use.','image'=>'/images/products/imports/limestone/lime-3.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'2521','CaCO3'=>'≥ 94%','Size'=>'0-50mm','Moisture'=>'≤ 2%','Origin'=>'Oman / UAE']),'use_cases'=>json_encode(['Cement plant raw material','Industrial lime production','Water treatment','Soil stabilisation']),'tags'=>json_encode(['Construction','Limestone','Industrial']),'sort_order'=>4,'is_active'=>true],
            ['name'=>'Automobile Spare Parts','slug'=>'automobile-spare-parts','type'=>'import','category'=>'Automotive','detail_title'=>'Genuine & Quality Auto Spare Parts','icon'=>'🔧','description'=>'Genuine and quality automobile spare parts from Japan and Germany for Bangladesh\'s vehicle repair market.','image'=>'/images/hero/slides/service-auto-parts-1.png','gallery_images'=>json_encode([]),'specs'=>json_encode(['Origin'=>'Japan / Germany','Condition'=>'Genuine / Used','Coverage'=>'Cars, Trucks, Buses','Min Order'=>'1 FCL']),'use_cases'=>json_encode(['Vehicle repair and maintenance','Fleet management','Automotive workshops']),'tags'=>json_encode(['Automotive','Spare Parts','Import']),'sort_order'=>5,'is_active'=>true],
            ['name'=>'Geo Synthetic Materials','slug'=>'geo-synthetic-materials','type'=>'import','category'=>'Construction Materials','detail_title'=>'Geotextile & Geo Synthetic Solutions','icon'=>'🏗️','description'=>'Geotextile fabrics, geomembranes, and geo synthetic construction materials for infrastructure projects.','image'=>'/images/products/imports/aggregate/aggregate-3.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'5911.90','Type'=>'Woven / Non-woven / Composite','Application'=>'Road / Embankment / Landfill','Origin'=>'China / India']),'use_cases'=>json_encode(['Road and embankment reinforcement','Drainage and filtration','Landfill lining','Slope stabilisation']),'tags'=>json_encode(['Construction','Geosynthetic','Infrastructure']),'sort_order'=>6,'is_active'=>true],
            ['name'=>'Clinker','slug'=>'clinker','type'=>'import','category'=>'Construction Materials','detail_title'=>'Portland Cement Clinker','icon'=>'🏭','description'=>'Portland cement clinker for grinding stations and cement blending operations across Bangladesh.','image'=>'/images/products/imports/limestone/lime-1.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['HS Code'=>'2523.10','LSF'=>'0.92–0.98','C3S'=>'≥ 55%','Packing'=>'Bulk','Min Order'=>'5000 MT','Origin'=>'Vietnam / Thailand']),'use_cases'=>json_encode(['Cement grinding station input','Blended cement production','Concrete manufacturing']),'tags'=>json_encode(['Cement','Clinker','Construction']),'sort_order'=>7,'is_active'=>true],
            ['name'=>'Heavy Equipment','slug'=>'heavy-equipment','type'=>'import','category'=>'Machinery','detail_title'=>'Construction & Industrial Heavy Equipment','icon'=>'🚜','description'=>'Construction and industrial heavy machinery including excavators, loaders, cranes, and generators.','image'=>'/images/shipping/vessel-1.jpeg','gallery_images'=>json_encode([]),'specs'=>json_encode(['Condition'=>'New / Used','Origin'=>'Japan / South Korea / Germany','Lead Time'=>'30-90 days','Min Order'=>'1 unit']),'use_cases'=>json_encode(['Construction site operations','Port and material handling','Industrial plant operations','Infrastructure projects']),'tags'=>json_encode(['Machinery','Equipment','Heavy']),'sort_order'=>8,'is_active'=>true],
        ];
        foreach ($products as $p) { Product::create($p); }
    }
}
